[package]
name = "fuel_logger-telegram_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.2.12", features = ["postgres", "time"] }
dotenv = "0.15.0"
dotenvy = "0.15.7"
frankenstein = "0.44.0"
log = "0.4.27"
lovely_env_logger = "0.6.2"
time = { version = "0.3.42", features = ["macros", "parsing", "formatting"] }
